[versions]
gradle_plugin = "8.3.0"
kotlin = "1.9.22"
core_ktx = "1.12.0"

[libraries]
androidx_core_ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core_ktx" }

[plugins]
application_plugin = { id = "com.android.application", version.ref = "gradle_plugin" }
kotlin_android_plugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android_library_plugin = { id = "com.android.library", version.ref = "gradle_plugin" }
